services:
  web:
    image: nestjs-backend-base
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      .env
    ports:
    - 3000:3000
    expose:
      - '3000'
    volumes:
      - .:/app
      - /app/node_modules
